spring:
  application:
    name: api
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

server:
  servlet:
    context-path: /icpms-api

app:
  jwt:
    expiration-ms: 3600000
    refresh-expiration-ms: 604800000
    issuer: icpms-api
  operation:
    license-key: testing001

logging:
  level:
    org.flexitech.projects.icpms: DEBUG
    org.springframework.security: INFO