server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/icpms?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: flexitech
    password: o;Ry)0=u>Ncc+pS#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false

image:
  path: /home/tomcat/icpms/images
  context:
    path: icpms-images

app:
  jwt:
    secret: c2VjdXJlLXNlY3JldC1rZXktZm9yLWljcG1zLWFwaS1hdC1sZWFzdC01MTItYml0cy1sb25nLWZvci1oczUxMi1zaWduaW5n

logging:
  level:
    org.flexitech.projects.icpms: INFO